// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2GCuXsw0R6H8Dw2dORntcoWcvBUor4ys',
    appId: '1:188919531334:web:66127b226dec74774a8747',
    messagingSenderId: '188919531334',
    projectId: 'boomhr2',
    authDomain: 'boomhr2.firebaseapp.com',
    storageBucket: 'boomhr2.appspot.com',
    measurementId: 'G-JEEGFVCZKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx-F7uXp0ZR1NZ1AXoTgkTop7vvEMJ6zg',
    appId: '1:188919531334:android:fa27839bee8e6c684a8747',
    messagingSenderId: '188919531334',
    projectId: 'boomhr2',
    storageBucket: 'boomhr2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkICrN4p150mxA_H1uEfLHTW1pI1PmxnY',
    appId: '1:188919531334:ios:cfd5906281fedb454a8747',
    messagingSenderId: '188919531334',
    projectId: 'boomhr2',
    storageBucket: 'boomhr2.appspot.com',
    iosClientId: '188919531334-bptmaa5d53gn1ljeklshhb0i71qdneb6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkICrN4p150mxA_H1uEfLHTW1pI1PmxnY',
    appId: '1:188919531334:ios:cfd5906281fedb454a8747',
    messagingSenderId: '188919531334',
    projectId: 'boomhr2',
    storageBucket: 'boomhr2.appspot.com',
    iosClientId: '188919531334-bptmaa5d53gn1ljeklshhb0i71qdneb6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
