// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl_JkDFiUPRqcnLQST-_sVOxASJTvXZ5k',
    appId: '1:140270447772:web:0a8df0a49b2c5db018d159',
    messagingSenderId: '140270447772',
    projectId: 'boom-hr',
    authDomain: 'boom-hr.firebaseapp.com',
    storageBucket: 'boom-hr.appspot.com',
    measurementId: 'G-5RZDNK2Y8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK7pE9ij0U7qUrb4ZcTwPtO1wp5hg2aOA',
    appId: '1:140270447772:android:c879f7e81e3b554a18d159',
    messagingSenderId: '140270447772',
    projectId: 'boom-hr',
    storageBucket: 'boom-hr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGig_O3uq0fYEkqhmKYRX-QYvHdRD83ZE',
    appId: '1:140270447772:ios:d822927b1c29661318d159',
    messagingSenderId: '140270447772',
    projectId: 'boom-hr',
    storageBucket: 'boom-hr.appspot.com',
    iosClientId: '140270447772-iq8p9sc17rqtpesrd0ps7me9cepell4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.boomhr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGig_O3uq0fYEkqhmKYRX-QYvHdRD83ZE',
    appId: '1:140270447772:ios:d822927b1c29661318d159',
    messagingSenderId: '140270447772',
    projectId: 'boom-hr',
    storageBucket: 'boom-hr.appspot.com',
    iosClientId: '140270447772-iq8p9sc17rqtpesrd0ps7me9cepell4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.boomhr',
  );
}
