// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIxGXt0iFeXA3Uo2i2LSKe0Cs27ez0Nbg',
    appId: '1:929938639530:web:3f3d94e80b71e3b191ded3',
    messagingSenderId: '929938639530',
    projectId: 'boomhr',
    authDomain: 'boomhr.firebaseapp.com',
    storageBucket: 'boomhr.appspot.com',
    measurementId: 'G-ER7N8S5H91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgAvYs1jOQSn05Nf41bNzuXcP0HtsboFI',
    appId: '1:929938639530:android:533c4822e2d176fe91ded3',
    messagingSenderId: '929938639530',
    projectId: 'boomhr',
    storageBucket: 'boomhr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa583NXUm1S-oQiE1qnCBaWf_0J3ZjqLk',
    appId: '1:929938639530:ios:c33fd4564f16675e91ded3',
    messagingSenderId: '929938639530',
    projectId: 'boomhr',
    storageBucket: 'boomhr.appspot.com',
    iosClientId: '929938639530-vg1eosddk2pk7to3sanskk5ukvn90dhs.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa583NXUm1S-oQiE1qnCBaWf_0J3ZjqLk',
    appId: '1:929938639530:ios:c33fd4564f16675e91ded3',
    messagingSenderId: '929938639530',
    projectId: 'boomhr',
    storageBucket: 'boomhr.appspot.com',
    iosClientId: '929938639530-vg1eosddk2pk7to3sanskk5ukvn90dhs.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
